### ISSUE TITLE
Bundle fonts for mobile apps

### ISSUE THREAD

**Issue by mozfet** [mozfet/ExpertBox#75]
# Description

Speed up Meteor Andoird and iOS apps to reduce bandwidth consumption by avoiding font loading from the web by embedding the Material Icons font into the project and remove the remote web font obtained from Google Fonts service. This approach also helps prevent 3rd party tracking of users.

# Notes

This already works well for the Roboto font family, however for some reason, it does not work easily with the Material Icons font family, and several previous attempts to do this failed before.

[Materialize CSS](http://materializecss.com/icons.html), give no instructions how to do this and points to [Google Fonts](https://google.github.io/material-design-icons/#icon-font-for-the-web), but so far unable to get it working in Meteor.

For previous project [zodiase:material-design-icons-fonts](https://atmospherejs.com/zodiase/material-design-icons-fonts) did the trick, however, it seems this no longer works well and that project seems a little stale. Zodiase still works in terms of achieving the result of packing fonts into the project, however, has serious drawbacks in causing [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) and shows words where the icon should be before the actual icons are shown. I also produce browser warnings (on DEV and PROD) regarding slow connections and stand-in fonts being used, and finally, it looks for fonts in the wrong places. For these reasons [zodiase:material-design-icons-fonts](https://atmospherejs.com/zodiase/material-design-icons-fonts) is not feasible for this project.

# Todo
- [ ] Remove the Google hosted font from ```/client/main.html ```
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
- [ ] Download the font [woff2](https://github.com/google/material-design-icons/raw/master/iconfont/MaterialIcons-Regular.woff2) [woff](https://github.com/google/material-design-icons/raw/master/iconfont/MaterialIcons-Regular.woff) [ttf](https://github.com/google/material-design-icons/raw/master/iconfont/MaterialIcons-Regular.ttf) [eot](https://github.com/google/material-design-icons/raw/master/iconfont/MaterialIcons-Regular.eot) 
- [ ] Store the font files in folder ```/public/fonts/materializeIcons/```
- [ ] Add the font face definition and CSS rules to ```/client/main.css```
```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url('/fonts/materialIcons/MaterialIcons-Regular.eot'); 
  src: local('Material Icons'),
    local('MaterialIcons-Regular'),
    url('/fonts/materialIcons/MaterialIcons-Regular.woff2') format('woff2'),
    url('/fonts/materialIcons/MaterialIcons-Regular.woff') format('woff'),
    url('/fonts/materialIcons/MaterialIcons-Regular.ttf') format('truetype');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
  font-feature-settings: 'liga';
}
```
